### ISSUE TITLE
Add ability to log to console only

### ISSUE THREAD

**Issue by gkallenberg** [NYPL/hold-request-service#12]
Posting log messages to Slack can be a performance drain especially if more verbose logging is needed for debugging/troubleshooting. The PHP starter provides the SlackHandler, but not all log messages need to post to Slack and can post to console/stdout only.

**Comment by kfriedman** [comment]
Yes! If you take a look at APILogger in the starter, you'll see that there's a separate log level for Slack so that can be report at a much higher level or, I guess, disabled altogether with a log level that can never be reached.
